title:              Krishna Khadka
email:              krishnakhadka2802@gmail.com
description:        I'm a Machine Learning Engineer ðŸš€
author:             Krishna Khadka
baseurl:            ""
url:                "https://khadkakrishna.github.io"

# Social Profiles
twitter_username:   
github_username:    khadkakrishna
facebook_username:  
instagram_username: 
linkedin_username:  kkhadka

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-QS9Q0J88B3 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           4
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
